<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>head_meta_name-ogtitle</name>
   <tag></tag>
   <elementGuidId>9427d48b-1a9f-490f-9643-c64f22b6d846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/head/meta[@name='og:title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/head/meta[@name='og:title']</value>
   </webElementProperties>
</WebElementEntity>
