<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>head_meta_property-ogtitle</name>
   <tag></tag>
   <elementGuidId>acdf593d-7653-4859-94d6-a9eef028dda6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/head/meta[@property='og:title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/head/meta[@property='og:title']</value>
   </webElementProperties>
</WebElementEntity>
